api/urls.py
from django.urls import path
from django.conf import settings
from strawberry.django.views import GraphQLView
from .schema import schema
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    path(
        "graphql",
        csrf_exempt(
            GraphQLView.as_view(
                schema=schema,
                graphql_ide="graphiql" if settings.DEBUG else None,
            )
        ),
    ),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin_url = f"{settings.DJANGO_ADMIN_URL.strip('/')}/"

urlpatterns = [
    path(admin_url, admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("api.urls")),
    path("", include("guard.urls")),
    path("", include("shared.urls")),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guard/urls.py
from django.urls import path, include

from .views import (
    DashboardView,
    SubscribersListView,
    LocationsListView,
    LocationCreateView,
    LocationUpdateView,
    LocationDeleteView,
    EventListView,
    EventCreateView,
    EventUpdateView,
    EventDeleteView,
    TipsListView,
    TipCreateView,
    TipUpdateView,
    TipDeleteView,
    HikingListView,
    HikingCreateView,
    HikingUpdateView,
    HikingDeleteView,
    AdListView,
    AdCreateView,
    AdUpdateView,
    AdDeleteView,
    EventTrackingView,
    AdTrackingView,
    PublicTransportListView,
    PublicTransportCreateView,
    PublicTransportUpdateView,
    PublicTransportDeleteView,
    PartnerListView,
    PartnerCreateView,
    PartnerUpdateView,
    PartnerDeleteView,
    SponsorListView,
    SponsorCreateView,
    SponsorUpdateView,
    SponsorDeleteView,
    get_cities_by_country,
    get_subregions_by_city,
    get_locations_by_city,
)

app_name = "guard"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path(
        "staff/",
        include(
            [
                path(
                    "subscribersList/",
                    SubscribersListView.as_view(),
                    name="subscribersList",
                ),
                path(
                    "locationsList/", LocationsListView.as_view(), name="locationsList"
                ),
                path(
                    "locations/create/",
                    LocationCreateView.as_view(),
                    name="location_create",
                ),
                path(
                    "locations/update/<int:pk>/",
                    LocationUpdateView.as_view(),
                    name="location_update",
                ),
                path(
                    "locations/delete/<int:pk>/",
                    LocationDeleteView.as_view(),
                    name="location_delete",
                ),
                path("eventsList/", EventListView.as_view(), name="eventsList"),
                path("events/create/", EventCreateView.as_view(), name="event_create"),
                path(
                    "events/update/<int:pk>/",
                    EventUpdateView.as_view(),
                    name="event_update",
                ),
                path(
                    "events/delete/<int:pk>/",
                    EventDeleteView.as_view(),
                    name="event_delete",
                ),
                path(
                    "events/track/<int:pk>/",
                    EventTrackingView.as_view(),
                    name="event_track",
                ),
                path("tips/", TipsListView.as_view(), name="tipsList"),
                path("tips/create/", TipCreateView.as_view(), name="tip_create"),
                path(
                    "tips/update/<int:pk>/", TipUpdateView.as_view(), name="tip_update"
                ),
                path(
                    "tips/delete/<int:pk>/", TipDeleteView.as_view(), name="tip_delete"
                ),
                path("hikings/", HikingListView.as_view(), name="hikingsList"),
                path(
                    "hikings/create/", HikingCreateView.as_view(), name="hiking_create"
                ),
                path(
                    "hikings/update/<int:pk>/",
                    HikingUpdateView.as_view(),
                    name="hiking_update",
                ),
                path(
                    "hikings/delete/<int:pk>/",
                    HikingDeleteView.as_view(),
                    name="hiking_delete",
                ),
                path(
                    "publicTransportsList/",
                    PublicTransportListView.as_view(),
                    name="publicTransportsList",
                ),
                path(
                    "publicTransports/create/",
                    PublicTransportCreateView.as_view(),
                    name="publicTransport_create",
                ),
                path(
                    "publicTransports/update/<int:pk>/",
                    PublicTransportUpdateView.as_view(),
                    name="publicTransport_update",
                ),
                path(
                    "publicTransports/delete/<int:pk>/",
                    PublicTransportDeleteView.as_view(),
                    name="publicTransport_delete",
                ),
                path("partners/", PartnerListView.as_view(), name="partnersList"),
                path(
                    "partners/create/",
                    PartnerCreateView.as_view(),
                    name="partner_create",
                ),
                path(
                    "partners/update/<int:pk>/",
                    PartnerUpdateView.as_view(),
                    name="partner_update",
                ),
                path(
                    "partners/delete/<int:pk>/",
                    PartnerDeleteView.as_view(),
                    name="partner_delete",
                ),
                path("sponsors/", SponsorListView.as_view(), name="sponsorsList"),
                path(
                    "sponsors/create/",
                    SponsorCreateView.as_view(),
                    name="sponsor_create",
                ),
                path(
                    "sponsors/update/<int:pk>/",
                    SponsorUpdateView.as_view(),
                    name="sponsor_update",
                ),
                path(
                    "sponsors/delete/<int:pk>/",
                    SponsorDeleteView.as_view(),
                    name="sponsor_delete",
                ),
            ]
        ),
    ),
    path("adsList/", AdListView.as_view(), name="adsList"),
    path("ads/create/", AdCreateView.as_view(), name="ad_create"),
    path("ads/update/<int:pk>/", AdUpdateView.as_view(), name="ad_update"),
    path("ads/delete/<int:pk>/", AdDeleteView.as_view(), name="ad_delete"),
    path("ads/track/<int:pk>/", AdTrackingView.as_view(), name="ad_track"),
    path(
        "api/cities/<int:country_id>/",
        get_cities_by_country,
        name="get_cities_by_country",
    ),
    path(
        "api/subregions/<int:city_id>/",
        get_subregions_by_city,
        name="get_subregions_by_city",
    ),
    path(
        "api/locations/<int:city_id>/",
        get_locations_by_city,
        name="get_locations_by_city",
    ),
]

shared/urls.py
from django.urls import path
from .views import (
    PageListView,
    CustomLoginView,
    CustomLogoutView,
    RegisterView,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    SettingView,
    PageCreateView,
    PageUpdateView,
    PageDeleteView,
    translate_text,
)

app_name = "shared"
urlpatterns = [
    path("pages/", PageListView.as_view(), name="pageList"),
    path("pages/create/", PageCreateView.as_view(), name="page_create"),
    path("pages/<int:pk>/update/", PageUpdateView.as_view(), name="page_update"),
    path("pages/<int:pk>/delete/", PageDeleteView.as_view(), name="page_delete"),
    path("api/translate/", translate_text, name="translate_text"),
    path("auth/login/", CustomLoginView.as_view(), name="login"),
    path("auth/logout/", CustomLogoutView.as_view(), name="logout"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    path(
        "auth/password-reset/", CustomPasswordResetView.as_view(), name="password_reset"
    ),
    path(
        "auth/password-reset/done/",
        CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "auth/password-reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "auth/password-reset/complete/",
        CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(
        "auth/password-change/",
        CustomPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "auth/password-change/done/",
        CustomPasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path("auth/settings/", SettingView.as_view(), name="settings"),
]

guard/templates/guard/views/pages/list.html
{% extends 'guard/base/index.html' %}
{% load static i18n %}

{% block title %}{% trans "Pages List" %}{% endblock title %}

{% block body %}
   <div class="inline-flex rounded-base -space-x-px" role="group">
      <a href="{% url 'shared:pageList' %}" class="inline-flex items-center text-heading bg-neutral-primary border border-dark-strong hover:bg-dark hover:text-white focus:ring-3 focus:ring-neutral-tertiary-soft font-medium leading-5 rounded-s-base text-sm px-3 py-2 focus:outline-none">
         <svg class="w-4 h-4 me-1.5" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-80q-33 0-56.5-23.5T120-160v-560q0-33 23.5-56.5T200-800h40v-80h80v80h320v-80h80v80h40q33 0 56.5 23.5T840-720v560q0 33-23.5 56.5T760-80H200Zm0-80h560v-400H200v400Zm0-480h560v-80H200v80Zm0 0v-80 80Z"/></svg>
         {% trans "List" %} 
      </a>
      <a href="{% url 'shared:page_create' %}" class="inline-flex items-center text-heading bg-neutral-primary border border-dark-strong hover:bg-dark hover:text-white focus:ring-3 focus:ring-neutral-tertiary-soft font-medium leading-5 rounded-e-base text-sm px-3 py-2 focus:outline-none">
         <svg class="w-4 h-4 me-1.5" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-440H200v-80h240v-240h80v240h240v80H520v240h-80v-240Z"/></svg>
         {% trans "Add" %}
      </a>
   </div>

   <div class="container py-6">
      
      <table id="page-list">
         <thead>
            <tr>
                  <th>
                     <span class="flex items-center">
                        {% trans "Title" %}
                        <svg class="w-4 h-4 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m8 15 4 4 4-4m0-6-4-4-4 4"/>
                        </svg>
                     </span>
                  </th>
                  <th>
                     <span class="flex items-center">
                        {% trans "Slug" %}
                        <svg class="w-4 h-4 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m8 15 4 4 4-4m0-6-4-4-4 4"/>
                        </svg>
                     </span>
                  </th>
                  <th>
                     <span class="flex items-center">
                        {% trans "Status" %}
                        <svg class="w-4 h-4 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m8 15 4 4 4-4m0-6-4-4-4 4"/>
                        </svg>
                     </span>
                  </th>
                  <th>
                     <span class="flex items-center">
                        {% trans "Created At" %}
                        <svg class="w-4 h-4 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m8 15 4 4 4-4m0-6-4-4-4 4"/>
                        </svg>
                     </span>
                  </th>
                  <th></th>
            </tr>
         </thead>
         <tbody>
            {% for data in pages %}
               <tr>
                     <td class="font-medium text-heading whitespace-nowrap">{{ data.title }}</td>
                     <td>{{ data.slug }}</td>
                     <td>
                        {% if data.is_active %}
                           <span class="bg-green-100 text-green-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-green-900 dark:text-green-300">{% trans "Active" %}</span>
                        {% else %}
                           <span class="bg-red-100 text-red-800 text-xs font-medium px-2.5 py-0.5 rounded dark:bg-red-900 dark:text-red-300">{% trans "Inactive" %}</span>
                        {% endif %}
                     </td>
                     <td>{{ data.created_at|date:"Y-m-d" }}</td>
                     <td>
                        <div class="flex items-center gap-2">
                           <a href="{% url 'shared:page_update' data.id %}" class="inline-flex items-center text-white bg-brand box-border border border-transparent hover:bg-brand-strong focus:ring-4 focus:ring-brand-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                              <svg class="w-3.5 h-3.5 me-1.5 -ms-0.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"  viewBox="0 0 640 640">
                                 <path d="M505 122.9L517.1 135C526.5 144.4 526.5 159.6 517.1 168.9L488 198.1L441.9 152L471 122.9C480.4 113.5 495.6 113.5 504.9 122.9zM273.8 320.2L408 185.9L454.1 232L319.8 366.2C316.9 369.1 313.3 371.2 309.4 372.3L250.9 389L267.6 330.5C268.7 326.6 270.8 323 273.7 320.1zM437.1 89L239.8 286.2C231.1 294.9 224.8 305.6 221.5 317.3L192.9 417.3C190.5 425.7 192.8 434.7 199 440.9C205.2 447.1 214.2 449.4 222.6 447L322.6 418.4C334.4 415 345.1 408.7 353.7 400.1L551 202.9C579.1 174.8 579.1 129.2 551 101.1L538.9 89C510.8 60.9 465.2 60.9 437.1 89zM152 128C103.4 128 64 167.4 64 216L64 488C64 536.6 103.4 576 152 576L424 576C472.6 576 512 536.6 512 488L512 376C512 362.7 501.3 352 488 352C474.7 352 464 362.7 464 376L464 488C464 510.1 446.1 528 424 528L152 528C129.9 528 112 510.1 112 488L112 216C112 193.9 129.9 176 152 176L264 176C277.3 176 288 165.3 288 152C288 138.7 277.3 128 264 128L152 128z"/>
                              </svg>
                              {% trans "Edit" %}
                           </a>
                           <button data-modal-target="confirm-modal{{ data.id }}" data-modal-toggle="confirm-modal{{ data.id }}" class="inline-flex items-center text-white bg-danger box-border border border-transparent hover:bg-danger-strong focus:ring-4 focus:ring-danger-medium shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 focus:outline-none">
                              <svg class="w-3.5 h-3.5 me-1.5 -ms-0.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 640 640">
                                 <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M232.7 69.9L224 96L128 96C110.3 96 96 110.3 96 128C96 145.7 110.3 160 128 160L512 160C529.7 160 544 145.7 544 128C544 110.3 529.7 96 512 96L416 96L407.3 69.9C402.9 56.8 390.7 48 376.9 48L263.1 48C249.3 48 237.1 56.8 232.7 69.9zM512 208L128 208L149.1 531.1C150.7 556.4 171.7 576 197 576L443 576C468.3 576 489.3 556.4 490.9 531.1L512 208z"/>
                              </svg>
                              {% trans "Delete" %}
                           </button>
                        </div>
                     </td>
               </tr>
               {% include "guard/views/pages/partials/confirm_model.html" with data=data %}
            {% endfor %}
         </tbody>
      </table>

   </div>
{% endblock body %}

{% block extrascript %}
   <script src="https://cdn.jsdelivr.net/npm/simple-datatables@9.0.3"></script>
   <script>

   if (document.getElementById("page-list") && typeof simpleDatatables.DataTable !== 'undefined') {
      const dataTable = new simpleDatatables.DataTable("#page-list", {
         searchable: true,
         perPageSelect: false
      });
   }
   </script>
{% endblock extrascript %}